name: Security Checks

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  code-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, python  # Change as per your project
 
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        
      - name: Fetch Code Scanning Alerts
        run: |
           curl -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/Champsec/ghas-demo/code-scanning/alerts \
               -o code-scanning-alerts.json
      - name: Upload Code Scanning Alerts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: code-scanning-alerts
          path: code-scanning-alerts.json

  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Secret Scan
        uses: trufflesecurity/trufflehog@v3.88.25

      - name: Easy detect-secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0
          
      - name: Fetch Secret Scanning Alerts
        run: |
          curl -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/Champsec/ghas-demo/secret-scanning/alerts \
               -o secret-scanning-alerts.json
      - name: Upload Secret Scanning Alerts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: secret-scanning-alerts
          path: secret-scanning-alerts.json

  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch Dependabot Alerts
        run: |
          curl -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/Champsec/ghas-demo/dependabot/alerts \
               -o dependabot-alerts.json
      - name: Upload Dependabot Alerts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dependabot-alerts
          path: dependabot-alerts.json
